jobs:
  - job: Windows
    pool:
      name: Hosted VS2017
    steps:
      - task: NodeTool@0
        displayName: 'Use Node 12.x'
        inputs:
          versionSpec: 12.x
      - script: 'yarn install'
        displayName: 'Install dependencies'
      - script: 'yarn test'
        displayName: 'Run tests'
  - job: macOS
    pool:
      name: Hosted macOS
    steps:
      - task: NodeTool@0
        displayName: 'Use Node 12.x'
        inputs:
          versionSpec: 12.x
      - script: 'yarn install'
        displayName: 'Install dependencies'
      - script: 'yarn test'
        displayName: 'Run tests'
  - job: Linux
    pool:
      name: Hosted Ubuntu 1604
    steps:
      - task: NodeTool@0
        displayName: 'Use Node 12.x'
        inputs:
          versionSpec: 12.x
      - script: 'yarn install'
        displayName: 'Install dependencies'
      - script: |
          set -e
          /usr/bin/Xvfb :10 -ac >> /tmp/Xvfb.out 2>&1 &
          disown -ar
        displayName: 'Start xvfb'
      - script: 'yarn test'
        displayName: 'Run tests'
        env:
          DISPLAY: :10
trigger:
  branches:
    include:
      - '*'
pr:
  branches:
    include:
      - '*'
